name: DEPLOY
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: /
        remote_path: /home/semestat/whatsapp.semestateknologiutama.com/
        remote_host: semestateknologiutama.com
        remote_user: semestat
        remote_key: ${{ secrets.DEPLOY_KEY }}
